# allow the mouse to scroll
setw -g mouse on

# set colors
set -g default-terminal "xterm-256color"

# select the color of the bar # NOTE: should not match other colors it the PS1 variable
set -g status-bg cyan

